1. Измените функцию `calc_logloss` так, чтобы нули по возможности не попадали в `np.log` (как вариант - использовать `np.clip` или `np.where`).  
2. На данных из урока изучите влияние гиперпараметров на ошибку алгоритма. Подберите аргументы функции `eval_LR_model` для логистической регрессии таким образом, чтобы log loss не превышал значение `0.3` `(0.1).` Как изменились веса?
3. Создайте функцию `calc_pred_proba`, возвращающую предсказанную вероятность класса "1". На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией `eval_LR_model`.
4. Создайте функцию `calc_pred`, возвращающую предсказанные классы (0 или 1). На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией `eval_LR_model`, а также порог вероятности.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],  
              [500, 700, 750, 600, 1450,        
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], 
              dtype = np.float64).T 

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [21]:
def standardization(x: np.ndarray) -> np.ndarray:
    s = (x - x.mean()) / x.std()
    return s

In [22]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log (как вариант - использовать np.clip или np.where).

In [16]:
def calc_logloss(y, y_pred):
    y_pred = np.clip(y_pred, a_min = 1e-10, a_max = 1 - 1e-10)
    err = np.mean(- y * np.log(y_pred) - (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [18]:
calc_logloss(y=0, y_pred=1)

23.02585084720009

На данных из урока изучите влияние гиперпараметров на ошибку алгоритма. Подберите аргументы функции eval_LR_model для логистической регрессии таким образом, чтобы log loss не превышал значение 0.3 (0.1). Как изменились веса?

In [20]:
def eval_LR_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    for i in range(1, iterations + 1):
        z = np.dot(X, w) # log(p/(1-p))
        y_pred = sigmoid(z) # p [0, 1]
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

In [23]:
X_st = X.copy()
X_st[:, 2] = standardization(X[:, 2])
X_st[:, 2]

array([-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
       -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735])

In [24]:
w = eval_LR_model(X_st, y, 1000, 1e-1)

100 [-0.29848458 -0.72686866  1.06314016  1.39690737] 0.5235767485993659
200 [-0.64245884 -0.81575707  1.11680356  1.72702881] 0.4995552177931558
300 [-0.95659618 -0.87689661  1.10232809  2.00636498] 0.4814150662731218
400 [-1.25432451 -0.91736333  1.05455726  2.24457861] 0.4664467561141666
500 [-1.5375957  -0.94440497  0.98735478  2.45373702] 0.4535011239613408
600 [-1.80755433 -0.96270374  0.90904148  2.64183838] 0.44201377632900957
700 [-2.06512906 -0.9753011   0.82492184  2.81420765] 0.4316738793739683
800 [-2.31113497 -0.98420861  0.73842971  2.97447927] 0.42228858977623335
900 [-2.54631605 -0.99077064  0.65178699  3.12518707] 0.4137239929669819
1000 [-2.77136565 -0.99588853  0.56641089  3.26813012] 0.40587815270727734


In [26]:
w = eval_LR_model(X_st, y, 1800, 2e-1)

180 [-1.13744976 -0.90355068  1.07722179  2.1542694 ] 0.4722605405250192
360 [-2.11579902 -0.97751433  0.80783245  2.8477759 ] 0.42979798717663387
540 [-2.94521466 -0.99942741  0.49947405  3.37829663] 0.4001108755016035
720 [-3.65769882 -1.01278173  0.22101757  3.83182834] 0.3780758609338283
900 [-4.27867642 -1.02709286 -0.01948026  4.23672745] 0.36115860613976775
1080 [-4.82811599 -1.04361726 -0.22733935  4.605436  ] 0.3477631451858543
1260 [-5.32127303 -1.06186121 -0.40937339  4.94523977] 0.33685309338514746
1440 [-5.76966651 -1.08117986 -0.57126497  5.26128164] 0.32774335343290284
1620 [-6.18200104 -1.10108761 -0.71732969  5.5575059 ] 0.3199709928808237
1800 [-6.56490521 -1.12126342 -0.85078204  5.83703416] 0.3132156797332823


In [29]:
w = eval_LR_model(X_st, y, 2000, 2e-1)

200 [-1.25475108 -0.91775717  1.05510451  2.24546166] 0.4665550707802968
400 [-2.31172961 -0.98436104  0.73845826  2.97508008] 0.4223547031209668
600 [-3.19432839 -1.00405047  0.40240132  3.53607427] 0.39206657103071746
800 [-3.94367938 -1.01887148  0.10965898  4.01686396] 0.3700362674045604
1000 [-4.59167819 -1.03602019 -0.13853495  4.44549975] 0.3533582423197489
1200 [-5.16236384 -1.05563116 -0.35118429  4.83483613] 0.3402614620864453
1400 [-5.67340922 -1.07682169 -0.53678932  5.19288695] 0.3296385294100061
1600 [-6.1377458  -1.09885773 -0.70177395  5.52546775] 0.320779451916748
1800 [-6.56490521 -1.12126342 -0.85078204  5.83703416] 0.3132156797332823
2000 [-6.96200326 -1.1437517  -0.98717545  6.13106725] 0.3066288709443726


In [30]:
w = eval_LR_model(X_st, y, 2000, 3e-1)

200 [-1.80869507 -0.96324939  0.90956419  2.64339334] 0.4421769355650185
400 [-3.19509128 -1.00410899  0.40218374  3.53663094] 0.3921061065318555
600 [-4.27946848 -1.02711567 -0.01977978  4.23725427] 0.3611798085105197
800 [-5.16314175 -1.05565711 -0.35147622  4.83536803] 0.34027386616759003
1000 [-5.91150573 -1.08780162 -0.62180568  5.36258931] 0.3250299580423656
1200 [-6.5656299  -1.12130072 -0.85103645  5.83756294] 0.31322088669455994
1400 [-7.15171659 -1.15501146 -1.05168024  6.27291288] 0.30363323625531835
1600 [-7.68700661 -1.18841682 -1.23160758  6.67747871] 0.29556265792914127
1800 [-8.18321983 -1.22129592 -1.39597104  7.05757416] 0.28857667022864925
2000 [-8.64856652 -1.25356526 -1.54827565  7.41779614] 0.28239662161439777


In [46]:
w = eval_LR_model(X_st, y, 10000, 1.5)

1000 [-14.33659933  -1.70691746  -3.32731109  11.96451936] 0.2240380111168329
2000 [-20.4029256   -2.2302234   -5.14707419  16.88431408] 0.18056136013315316
3000 [-24.9710286   -2.63165769  -6.48985807  20.58832391] 0.15606292777322706
4000 [-28.64763931  -2.95640633  -7.55872608  23.56418832] 0.14026159180436346
5000 [-31.73627959  -3.22912056  -8.45086017  26.05879037] 0.1291471392292976
6000 [-34.41139591  -3.46447278  -9.22067269  28.21434743] 0.12083294246947014
7000 [-36.78148572  -3.67178761  -9.90139217  30.1193971 ] 0.11432304389909831
8000 [-38.91815874  -3.85731491 -10.51464854  31.832412  ] 0.10904458548220283
9000 [-40.8709429   -4.02542927 -11.07523769  33.39385591] 0.10464537539424738
10000 [-42.6754094   -4.17930416 -11.59368902  34.83280672] 0.10089708998185384


Значение ошибки 0.3 мы достигли при альфа = 0,2 и кол-во итераций равное 2000. Первые три веса уменьшились, а последний возрос. 
Значение ошибки 0.1 мы достигли при альфа = 1,5 и кол-во итераций равное 10000.
Так же первые три веса стали очень малы, а последний очень сильно возрос. 

Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса "1". На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией eval_LR_model.

In [54]:
def calc_pred_proba(w, X):
    return sigmoid(np.dot(X_st, w))
calc_pred_proba(w, X_st)

array([0.25923192, 0.25771377, 0.89560388, 0.25847212, 0.74923008,
       0.4913075 , 0.96354811, 0.13232747, 0.25961237, 0.89467452])

Создайте функцию calc_pred, возвращающую предсказанные классы (0 или 1). На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией eval_LR_model, а также порог вероятности.

In [55]:
def calc_pred(w, X):
  pred = sigmoid(np.dot(X_st, w))
  pred.round(2)
  return np.where(pred > 0.5, 1, 0)
calc_pred(w, X_st)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])